### ISSUE TITLE
The action is broken

### ISSUE THREAD

**Issue by sleshchenko** [shivanshs9/setup-k8s-operator-sdk#4]
The action seems to fail with the error `File not found: '/home/runner/work/_actions/shivanshs9/setup-k8s-operator-sdk/v1.1.3/dist/index.js'`

See the example run https://github.com/sleshchenko/setup-k8s-operator-sdk/actions/runs/550641059

**Comment by shivanshs9** [comment]
@sleshchenko sorry for the delay, should be fixed now in v1.1.4
